# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Layton Everson - Developing away... 
email: layton.everson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Layton Everson is a web developer seasoned for over 10 years. He excells in backend systems 
  taylored to business processes. He is extreamly proficient in PHP w/Symfony, Zend Framework 2
  cakePhp, and custom or propritary frameworks; Mysql and Doctrine2; Application Design, planning
  and specifications; Team Managment, training, repository managment, leadership, etc. Layton 
  enjoys taking a business processes and streamlining them in his applications. He is great to 
  have around for business meetings, application planning, and for any related advise. 
baseurl: ""
url: "http://laytoneverson.github.io" # the base hostname & protocol for your site
twitter_username: laytone
github_username:  laytoneverson

# Build settings
markdown: kramdown
